var Generator = require('yeoman-generator');
const path = require('path');

module.exports = class extends Generator {
	constructor(args, opts) {
		super(args, opts);
		this.appName = path.basename(process.cwd());
		this.appAuthor = "Richard Billion";
	}

	initializing() {
		this.log('begin ...');
	}

	configuring() {
		let defaultSettings = this.fs.readJSON(this.templatePath('src/package.json'));

	// 	let packageSettings = {
	// 		name: this.appName,
	// 		private: true,
	// 		version: '0.0.1',
	// 		description: `${this.appName} - Generated by yeoman`,
	// 		main: 'index.js',
	// 		scripts: defaultSettings.scripts,
	// 		author: this.appAuthor,
	// 		dependencies: defaultSettings.dependencies,
	// 		devDependencies: defaultSettings.devDependencies
	// 	};

	// 	this.fs.writeJSON(this.destinationPath('package.json', packageSettings));
	}

	writting() {
		// fs.mkdirSync('dist')
		this.fs.copy(this.templatePath('src'), this.destinationPath());
		this.fs.copyTpl(this.templatePath('src/babelrc.tpl'), this.destinationPath('.babelrc'));
		this.fs.copyTpl(this.templatePath('src/gitignore.tpl'), this.destinationPath('.gitignore'));
	}

	install() {
	    // 安装 package 安装.
	    this.installDependencies({ bower: false });
	  }

};